# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Meta": "00_core.ipynb",
         "meta": "00_core.ipynb",
         "step_rename_cols": "00_core.ipynb",
         "step_replace_missing_with_nan": "00_core.ipynb",
         "step_remove_not_needed_cols": "00_core.ipynb",
         "step_remove_rows_with_missing_ids": "00_core.ipynb",
         "step_remove_duplicate_rows": "00_core.ipynb",
         "step_format_dates": "00_core.ipynb",
         "step_format_round_numeric_cols": "00_core.ipynb",
         "step_change_dtypes": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://tkanngiesser.github.io/dproc/"

git_url = "https://github.com/tkanngiesser/dproc/tree/master/"

def custom_doc_links(name): return None
